# Generated by Django 4.2 on 2023-04-25 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('afyaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('registered_on', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_health', models.IntegerField(choices=[(1, 'good'), (2, 'poor'), (0, 'undefined')], default=0)),
                ('is_onDiet', models.IntegerField(blank=True, choices=[(1, 'yes'), (2, 'no'), (0, 'doubtful')], default=((1, 'yes'), (2, 'no'), (0, 'doubtful')), null=True)),
                ('is_onDrugs', models.IntegerField(blank=True, choices=[(1, 'yes'), (2, 'no'), (0, 'doubtful')], default=((1, 'yes'), (2, 'no'), (0, 'doubtful')), null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afyaapp.patientinformation')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('body_mass_index', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afyaapp.patientinformation')),
            ],
        ),
    ]
