# Generated by Django 4.2 on 2023-04-26 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('afyaapp', '0002_patientinformation_patientrecord_appointmentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetails',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
