# Generated by Django 4.2 on 2023-04-20 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('afyaapp', '0003_alter_appointmentdetails_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='patient',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='afyaapp.patientinformation'),
            preserve_default=False,
        ),
    ]
