# Generated by Django 4.2 on 2023-05-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afyaapp', '0003_appointmentdetails_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentdetails',
            old_name='created_on',
            new_name='appointment_date',
        ),
    ]
