# Generated by Django 4.2 on 2023-05-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afyaapp', '0004_rename_created_on_appointmentdetails_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='appointment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
